# Лабораторная работа №1
## Выполнила студентка группы БВТ2001 Моисеева Надежда Александровна
### Задание 1

In [1]:
print("Hello, world!")

Hello, world!


### Задание 2

In [2]:
from random import randint
import numpy as np
import time
m, n , min_limit, max_limit = map(int, input("Введите числа:").split()) 
a = []
for i in range(m*n):
    a.append(randint(min_limit,max_limit))
counter = 0


counter = 0
a_np = np.zeros((m,n))
for i in range (m):
    for j in range (n):
        a_np[i][j] = a[counter]
        counter += 1
print ("Numpy матрица")
print(a_np)

Введите числа:100 1000 1 121
Numpy матрица
[[ 66.  72.  33. ...  63.  79.  93.]
 [ 21.  19. 116. ...  42.  61.  23.]
 [  8.  56.  10. ...  58.   8.  81.]
 ...
 [ 77. 105. 105. ...  41.  90.  45.]
 [ 64.  62.  52. ...  61.  95.  78.]
 [107.  70. 112. ...  77.  17.  78.]]


### Задание 3

#### Встроенная сортировка

In [3]:
tik1 = time.perf_counter()
a_np_sorted = np.sort(a)
tok1 = time.perf_counter()
counter = 0
a_np_s_b = np.zeros((m,n))

for i in range (m):
    for j in range (n):
        a_np_s_b[i][j] = a_np_sorted[counter]
        counter += 1

        
diff1 = tok1-tik1

print(f"Вычисление заняло {tok1 - tik1:0.10f} секунд")
#a_np_s_b

Вычисление заняло 0.0099562000 секунд


#### Выбором

In [6]:
# создаём функцию-сортировщик
def select (a = list):
    index = 0 # переменная минимального индекса
    tech = 0
    for i in range (len(a)): # идём по массиву
        index = i
        for j in range (i+1,len(a)): # находим минимальное значение
            if a[j]<a[index] :
                index = j
        tech = a[index] # меняем местами числа
        a[index] = a[i]
        a[i] = tech # эти 3 строчки можно упростить
    
    return a

tik2 = time.perf_counter()
a_sort_select = select(a) # отсортированный массив
tok2 = time.perf_counter()

a_matrix_select = np.zeros((m,n)) # матрица

#print(a_sort_select)

counter = 0
for i in range (m):
    for j in range (n):
        a_matrix_select[i][j] = a_sort_select[counter]
        counter += 1

diff2 = tok2-tik2

print(f"Вычисление заняло {tok2 - tik2:0.10f} секунд")
#a_matrix_select # вывод матрицы

Вычисление заняло 510.3804299000 секунд


#### Вставкой

In [5]:
def insert (a = list):
    for i in range(1,len(a)-1): #идём по массиву
        znach = a[i]
        j = i - 1

        while j >= 0 and a[j] >= a[i]: # идём по отсортированной части
            a[j+1] = a[j]
            j -= 1
        a[j + 1] = znach
    return a

tik3 = time.perf_counter()
a_sort_insert = insert(a)
tok3 = time.perf_counter()

a_matrix_insert = np.zeros((m,n)) # матрица

#print(a_sort_insert)

counter = 0
for i in range (m):
    for j in range (n):
        a_matrix_insert[i][j] = a_sort_insert[counter]
        counter += 1

diff3 = tok3-tik3

print(f"Вычисление заняло {tok3 - tik3:0.10f} секунд")
#a_matrix_insert # вывод матрицы

Вычисление заняло 14.5350902000 секунд


#### Обменом

In [18]:
def exchange(a = list):
    for i in range (len(a)-1):
        for j in range (i+1,len(a)):
            if a[i] > a[j]:
                a[j],a[i] = a[i], a[j]
    
    return a


tik4 = time.perf_counter()
a_sort_exch = exchange(a)
tok4 = time.perf_counter()


a_matrix_exch = np.zeros((m,n)) # матрица

#print(a_sort_exch)

counter = 0
for i in range (m):
    for j in range (n):
        a_matrix_exch[i][j] = a_sort_exch[counter]
        counter += 1

diff4 = tok4-tik4
print(f"Вычисление заняло {tok4 - tik4:0.10f} секунд")        
#a_matrix_exch # вывод матрицы

Вычисление заняло 0.0043573000 секунд


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,
         3.,  3.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
         5.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  7.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.,  8.,
         9.,  9.,  9.,  9.,  9., 10., 10., 10., 10., 10., 10., 10., 10.,
        11., 11., 11., 11.],
       [12., 12., 12., 13., 13., 13., 13., 13., 13., 13., 13., 14., 14.,
        14., 14., 14., 15., 15., 15., 15., 16., 16., 16., 16., 17., 17.,
        17., 17., 17., 17.],
       [17., 17., 18., 18., 18., 18., 19., 19., 19., 19., 19., 19., 19.,
        19., 19., 20., 20., 20., 20., 20., 20., 21., 21., 21., 21., 21.,
        21., 22., 22., 22.],
       [22., 22., 23., 23., 23., 24., 24., 24., 24., 24., 24., 24., 24.,
        25., 25., 25., 26., 26., 26., 26., 27., 27., 27., 27., 27., 27.,
        27., 27., 27., 27.],
       [28., 28., 28., 28., 28., 28., 28., 28., 29., 29., 30., 30., 30.,
        30., 30., 30., 31., 31., 31., 31., 31., 31.,

#### Шелла

In [19]:
def shell(a):
    inc = len(a) // 2
    while inc:
        for i, el in enumerate(a):
            while i >= inc and a[i - inc] > el:
                a[i] = a[i - inc]
                i -= inc
            a[i] = el
        inc = 1 if inc == 2 else int(inc * 5.0 / 11)
    return a


tik5 = time.perf_counter()
a_sort_shell = shell(a)
tok5 = time.perf_counter()

a_matrix_shell = np.zeros((m,n)) # матрица

#print(a_sort_shell)

counter = 0
for i in range (m):
    for j in range (n):
        a_matrix_shell[i][j] = a_sort_shell[counter]
        counter += 1

diff5 = tok5-tik5     
print(f"Вычисление заняло {tok5 - tik5:0.10f} секунд")

#a_matrix_shell # вывод матрицы

Вычисление заняло 0.0004561000 секунд


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,
         3.,  3.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
         5.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  7.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.,  8.,
         9.,  9.,  9.,  9.,  9., 10., 10., 10., 10., 10., 10., 10., 10.,
        11., 11., 11., 11.],
       [12., 12., 12., 13., 13., 13., 13., 13., 13., 13., 13., 14., 14.,
        14., 14., 14., 15., 15., 15., 15., 16., 16., 16., 16., 17., 17.,
        17., 17., 17., 17.],
       [17., 17., 18., 18., 18., 18., 19., 19., 19., 19., 19., 19., 19.,
        19., 19., 20., 20., 20., 20., 20., 20., 21., 21., 21., 21., 21.,
        21., 22., 22., 22.],
       [22., 22., 23., 23., 23., 24., 24., 24., 24., 24., 24., 24., 24.,
        25., 25., 25., 26., 26., 26., 26., 27., 27., 27., 27., 27., 27.,
        27., 27., 27., 27.],
       [28., 28., 28., 28., 28., 28., 28., 28., 29., 29., 30., 30., 30.,
        30., 30., 30., 31., 31., 31., 31., 31., 31.,

#### Турнирная

In [20]:
def tournament_sort(arr:list):
    tree = [None]*2*(len(arr)+len(arr)%2)
    index = len(tree) - len(arr) - len(arr)%2
    
    for ix, el in enumerate(arr):
        tree[index+ix] = (ix,el)
    
    for j in range(len(arr)):
        n = len(arr)
        index = len(tree) - len(arr) - len(arr)%2
        while index > -1:
            n = (n+1)//2
            for ix in range(n):
                ix = max(index+ix*2, 1)
                if tree[ix] is not None and tree[ix+1] is not None:
                    tree[ix//2] = tree[ix+(tree[ix][1]>=tree[ix+1][1])]
                else:
                    tree[ix//2] = tree[ix] if tree[ix] is not None else tree[ix+1]
            index -= n
        index,x = tree[0]
        
        arr[j] = x
        tree[len(tree) - len(arr) - len(arr)%2 + index] = None
    return arr


tik6= time.perf_counter()
a_sort_tour = tournament_sort(a)
tok6 = time.perf_counter()

diff6 = tok6-tik6

a_matrix_tour = np.zeros((m,n)) # матрица

counter = 0
for i in range (m):
    for j in range (n):
        a_matrix_tour[i][j] = a_sort_tour[counter]
        counter += 1
        

print(f"Вычисление заняло {tok6 - tik6:0.10f} секунд")
#a_matrix_tour

Вычисление заняло 0.0663349000 секунд


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,
         3.,  3.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
         5.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  7.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.,  8.,
         9.,  9.,  9.,  9.,  9., 10., 10., 10., 10., 10., 10., 10., 10.,
        11., 11., 11., 11.],
       [12., 12., 12., 13., 13., 13., 13., 13., 13., 13., 13., 14., 14.,
        14., 14., 14., 15., 15., 15., 15., 16., 16., 16., 16., 17., 17.,
        17., 17., 17., 17.],
       [17., 17., 18., 18., 18., 18., 19., 19., 19., 19., 19., 19., 19.,
        19., 19., 20., 20., 20., 20., 20., 20., 21., 21., 21., 21., 21.,
        21., 22., 22., 22.],
       [22., 22., 23., 23., 23., 24., 24., 24., 24., 24., 24., 24., 24.,
        25., 25., 25., 26., 26., 26., 26., 27., 27., 27., 27., 27., 27.,
        27., 27., 27., 27.],
       [28., 28., 28., 28., 28., 28., 28., 28., 29., 29., 30., 30., 30.,
        30., 30., 30., 30., 30., 30., 30., 30., 30.,

#### Быстрая сортировка

In [21]:
def quick(list):
    if len(list) <= 1:
        return list
    else:
        less = []
        greater = []
        med = []
        point = list[0]
        
        for i in list:
            if i == point:
                med.append(i)
            elif i > point:
                greater.append(i)
            else:
                less.append(i)
    return quick(less) + med + quick(greater)
            
    
    
tik7 = time.perf_counter()
a_quicksort = quick(a)
tok7 = time.perf_counter()

diff7 = tok7-tik7

a_quicksort_m = np.zeros((m,n)) # матрица



counter = 0
for i in range (m):
    for j in range (n):
        a_quicksort_m[i][j] = a_quicksort[counter]
        counter += 1
        
        
print(f"Вычисление заняло {tok7 - tik7:0.10f} секунд")
#a_quicksort_m

Вычисление заняло 0.0012758000 секунд


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,
         3.,  3.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
         5.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  7.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.,  8.,
         9.,  9.,  9.,  9.,  9., 10., 10., 10., 10., 10., 10., 10., 10.,
        11., 11., 11., 11.],
       [12., 12., 12., 13., 13., 13., 13., 13., 13., 13., 13., 14., 14.,
        14., 14., 14., 15., 15., 15., 15., 16., 16., 16., 16., 17., 17.,
        17., 17., 17., 17.],
       [17., 17., 18., 18., 18., 18., 19., 19., 19., 19., 19., 19., 19.,
        19., 19., 20., 20., 20., 20., 20., 20., 21., 21., 21., 21., 21.,
        21., 22., 22., 22.],
       [22., 22., 23., 23., 23., 24., 24., 24., 24., 24., 24., 24., 24.,
        25., 25., 25., 26., 26., 26., 26., 27., 27., 27., 27., 27., 27.,
        27., 27., 27., 27.],
       [28., 28., 28., 28., 28., 28., 28., 28., 29., 29., 30., 30., 30.,
        30., 30., 30., 30., 30., 30., 30., 30., 30.,

#### Пирамидальная

In [22]:
def heapsort(a):
    n = len(a)

    for i in range(n, -1, -1):
        heapify(a, n, i)

    for i in range(n-1, 0, -1):
        a[i], a[0] = a[0], a[i] 
        heapify(a, i, 0)
    return a


def heapify(a_list, n, i):
    largest = i 
    l = 2 * i + 1   
    r = 2 * i + 2   
    
    if l < n and a_list[i] < a_list[l]:
        largest = l
        
    if r < n and a_list[largest] < a_list[r]:
        largest = r  
    
    if largest != i:
        a_list[i],a_list[largest] = a_list[largest],a_list[i]
        heapify(a_list, n, largest)

tik8 = time.perf_counter()
a_heapsort = heapsort(a)
tok8 = time.perf_counter()

a_heapsort_m = np.zeros((m,n)) # матрица



counter = 0
for i in range (m):
    for j in range (n):
        a_heapsort_m[i][j] = a_heapsort[counter]
        counter += 1
        
        
diff8 = tok8-tik8
print(f"Вычисление заняло {tok8 - tik8:0.10f} секунд")
#a_heapsort_m

Вычисление заняло 0.0019803000 секунд


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,
         3.,  3.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
         5.,  6.,  6.,  6.],
       [ 6.,  6.,  6.,  7.,  7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.,  8.,
         9.,  9.,  9.,  9.,  9., 10., 10., 10., 10., 10., 10., 10., 10.,
        11., 11., 11., 11.],
       [12., 12., 12., 13., 13., 13., 13., 13., 13., 13., 13., 14., 14.,
        14., 14., 14., 15., 15., 15., 15., 16., 16., 16., 16., 17., 17.,
        17., 17., 17., 17.],
       [17., 17., 18., 18., 18., 18., 19., 19., 19., 19., 19., 19., 19.,
        19., 19., 20., 20., 20., 20., 20., 20., 21., 21., 21., 21., 21.,
        21., 22., 22., 22.],
       [22., 22., 23., 23., 23., 24., 24., 24., 24., 24., 24., 24., 24.,
        25., 25., 25., 26., 26., 26., 26., 27., 27., 27., 27., 27., 27.,
        27., 27., 27., 27.],
       [28., 28., 28., 28., 28., 28., 28., 28., 29., 29., 30., 30., 30.,
        30., 30., 30., 30., 30., 30., 30., 30., 30.,

#### Сравнение результатов всех сортировок

In [29]:
mass = [diff1,diff2,diff3,diff4,diff5,diff6,diff7,diff8]
print("Встроенная сортировка:",diff1," Сортировка выбором:",diff2," Сортировка вставкой:",diff3," Сортировка обменом:",diff4," Сортировка Шелла:",diff5," Турнирная сортировка:",diff6," Быстрая сортировка:",diff7," Пирамидальная сортировка:",diff8)
print("Минимальное время",min(mass))
print("Максимальное время",max(mass))
print("Встроенная сортировка является самой быстрой")

Встроенная сортировка: 0.00018260000001646404  Сортировка выбором: 0.00441280000001143  Сортировка вставкой: 0.00042810000002191373  Сортировка обменом: 0.004357300000037867  Сортировка Шелла: 0.0004560999999512205  Турнирная сортировка: 0.06633489999995845  Быстрая сортировка: 0.0012757999999735148  Пирамидальная сортировка: 0.001980299999900126
Минимальное время 0.00018260000001646404
Максимальное время 0.06633489999995845
Встроенная сортировка является самой быстрой
